//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSBBTextures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutfitNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutfitNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSBBTextures.OutfitNames", typeof(OutfitNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Béis.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negro.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daisy.
        /// </summary>
        internal static string Daisy {
            get {
                return ResourceManager.GetString("Daisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul y Blanco.
        /// </summary>
        internal static string DededeBlueWhite {
            get {
                return ResourceManager.GetString("DededeBlueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color de GameBoy.
        /// </summary>
        internal static string DededeGameBoy {
            get {
                return ResourceManager.GetString("DededeGameBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucio.
        /// </summary>
        internal static string Dirty {
            get {
                return ResourceManager.GetString("Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gris.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde/Béis.
        /// </summary>
        internal static string IkeGreen2 {
            get {
                return ResourceManager.GetString("IkeGreen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorra de entrenador.
        /// </summary>
        internal static string JiggleTrainerCap {
            get {
                return ResourceManager.GetString("JiggleTrainerCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombrero.
        /// </summary>
        internal static string JigglyCap {
            get {
                return ResourceManager.GetString("JigglyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flor en la cabeza.
        /// </summary>
        internal static string JigglyFlower {
            get {
                return ResourceManager.GetString("JigglyFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorro de dormir.
        /// </summary>
        internal static string JigglySleepingHat {
            get {
                return ResourceManager.GetString("JigglySleepingHat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caqui.
        /// </summary>
        internal static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color de GameBoy.
        /// </summary>
        internal static string KirbyGameBoy {
            get {
                return ResourceManager.GetString("KirbyGameBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul celeste.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luigi Fuego.
        /// </summary>
        internal static string LuigiFieryLuigi {
            get {
                return ResourceManager.GetString("LuigiFieryLuigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colores de Waluigi.
        /// </summary>
        internal static string LuigiWaluigi {
            get {
                return ResourceManager.GetString("LuigiWaluigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Fuego.
        /// </summary>
        internal static string MarioFiery {
            get {
                return ResourceManager.GetString("MarioFiery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colores de Wario.
        /// </summary>
        internal static string MarioWario {
            get {
                return ResourceManager.GetString("MarioWario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traje Abeja.
        /// </summary>
        internal static string NessBumbleBee {
            get {
                return ResourceManager.GetString("NessBumbleBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usado.
        /// </summary>
        internal static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocarina Of Time.
        /// </summary>
        internal static string Ocarina {
            get {
                return ResourceManager.GetString("Ocarina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naranja.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colores de Daisy.
        /// </summary>
        internal static string PeachDaisy {
            get {
                return ResourceManager.GetString("PeachDaisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandana.
        /// </summary>
        internal static string PikachuBandana {
            get {
                return ResourceManager.GetString("PikachuBandana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorra.
        /// </summary>
        internal static string PikachuCap {
            get {
                return ResourceManager.GetString("PikachuCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gafas.
        /// </summary>
        internal static string PikachuGoggles {
            get {
                return ResourceManager.GetString("PikachuGoggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosa.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morado.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rojo.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metroid Fusion.
        /// </summary>
        internal static string SamusFusion {
            get {
                return ResourceManager.GetString("SamusFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leopardo.
        /// </summary>
        internal static string SnakeLeopard {
            get {
                return ResourceManager.GetString("SnakeLeopard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rojo y Negro.
        /// </summary>
        internal static string SnakeRedBlack {
            get {
                return ResourceManager.GetString("SnakeRedBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link de NES.
        /// </summary>
        internal static string ToonLinkNES {
            get {
                return ResourceManager.GetString("ToonLinkNES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        internal static string WarioGeneral {
            get {
                return ResourceManager.GetString("WarioGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naranja y Azul.
        /// </summary>
        internal static string WarioOrangeBlue {
            get {
                return ResourceManager.GetString("WarioOrangeBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negro y Rojo.
        /// </summary>
        internal static string WarioRedBlack {
            get {
                return ResourceManager.GetString("WarioRedBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinación de Wario Land 2.
        /// </summary>
        internal static string WarioWarioLand2 {
            get {
                return ResourceManager.GetString("WarioWarioLand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinación de Wario Land 3.
        /// </summary>
        internal static string WarioWarioLand3 {
            get {
                return ResourceManager.GetString("WarioWarioLand3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wario Ware.
        /// </summary>
        internal static string WarioWarioWare {
            get {
                return ResourceManager.GetString("WarioWarioWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanco.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amarillo.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
