//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texturizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CharNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texturizer.CharNames", typeof(CharNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitán Falcon.
        /// </summary>
        internal static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rey Dedede.
        /// </summary>
        internal static string Dedede {
            get {
                return ResourceManager.GetString("Dedede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diddy Kong.
        /// </summary>
        internal static string Diddy {
            get {
                return ResourceManager.GetString("Diddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donkey Kong.
        /// </summary>
        internal static string Donkey {
            get {
                return ResourceManager.GetString("Donkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falco.
        /// </summary>
        internal static string Falco {
            get {
                return ResourceManager.GetString("Falco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox.
        /// </summary>
        internal static string Fox {
            get {
                return ResourceManager.GetString("Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Game &amp; Watch.
        /// </summary>
        internal static string GameWatch {
            get {
                return ResourceManager.GetString("GameWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganondorf.
        /// </summary>
        internal static string Ganon {
            get {
                return ResourceManager.GetString("Ganon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giga Bowser.
        /// </summary>
        internal static string GKoopa {
            get {
                return ResourceManager.GetString("GKoopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ike.
        /// </summary>
        internal static string Ike {
            get {
                return ResourceManager.GetString("Ike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirby.
        /// </summary>
        internal static string Kirby {
            get {
                return ResourceManager.GetString("Kirby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowser.
        /// </summary>
        internal static string Koopa {
            get {
                return ResourceManager.GetString("Koopa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucario.
        /// </summary>
        internal static string Lucario {
            get {
                return ResourceManager.GetString("Lucario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucas.
        /// </summary>
        internal static string Lucas {
            get {
                return ResourceManager.GetString("Lucas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luigi.
        /// </summary>
        internal static string Luigi {
            get {
                return ResourceManager.GetString("Luigi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario.
        /// </summary>
        internal static string Mario {
            get {
                return ResourceManager.GetString("Mario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marth.
        /// </summary>
        internal static string Marth {
            get {
                return ResourceManager.GetString("Marth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Knight.
        /// </summary>
        internal static string MetaKnight {
            get {
                return ResourceManager.GetString("MetaKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ness.
        /// </summary>
        internal static string Ness {
            get {
                return ResourceManager.GetString("Ness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach.
        /// </summary>
        internal static string Peach {
            get {
                return ResourceManager.GetString("Peach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pikachu.
        /// </summary>
        internal static string Pikachu {
            get {
                return ResourceManager.GetString("Pikachu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olimar.
        /// </summary>
        internal static string Pikmin {
            get {
                return ResourceManager.GetString("Pikmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pit.
        /// </summary>
        internal static string Pit {
            get {
                return ResourceManager.GetString("Pit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivysaur.
        /// </summary>
        internal static string PokeFushigisou {
            get {
                return ResourceManager.GetString("PokeFushigisou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charizard.
        /// </summary>
        internal static string PokeLizardon {
            get {
                return ResourceManager.GetString("PokeLizardon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenador Pokémon.
        /// </summary>
        internal static string PokeTrainer {
            get {
                return ResourceManager.GetString("PokeTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squirtle.
        /// </summary>
        internal static string PokeZenigame {
            get {
                return ResourceManager.GetString("PokeZenigame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers.
        /// </summary>
        internal static string Popo {
            get {
                return ResourceManager.GetString("Popo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jigglypuff.
        /// </summary>
        internal static string Purin {
            get {
                return ResourceManager.GetString("Purin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.O.B..
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samus.
        /// </summary>
        internal static string Samus {
            get {
                return ResourceManager.GetString("Samus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheik.
        /// </summary>
        internal static string Sheik {
            get {
                return ResourceManager.GetString("Sheik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake.
        /// </summary>
        internal static string Snake {
            get {
                return ResourceManager.GetString("Snake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic.
        /// </summary>
        internal static string Sonic {
            get {
                return ResourceManager.GetString("Sonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Suit Samus.
        /// </summary>
        internal static string SZeroSuit {
            get {
                return ResourceManager.GetString("SZeroSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon Link.
        /// </summary>
        internal static string ToonLink {
            get {
                return ResourceManager.GetString("ToonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wario.
        /// </summary>
        internal static string Wario {
            get {
                return ResourceManager.GetString("Wario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wario Man.
        /// </summary>
        internal static string WarioMan {
            get {
                return ResourceManager.GetString("WarioMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoshi.
        /// </summary>
        internal static string Yoshi {
            get {
                return ResourceManager.GetString("Yoshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelda.
        /// </summary>
        internal static string Zelda {
            get {
                return ResourceManager.GetString("Zelda", resourceCulture);
            }
        }
    }
}
