//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texturizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texturizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texturizer para Super Smash Bros. Brawl..
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar.
        /// </summary>
        internal static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociando datos PAC.
        /// </summary>
        internal static string AssociatingPacData {
            get {
                return ResourceManager.GetString("AssociatingPacData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociando datos PCS.
        /// </summary>
        internal static string AssociatingPcsData {
            get {
                return ResourceManager.GetString("AssociatingPcsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar automáticamente el retrato correspondiente a la textura seleccionada.
        ///Si existe una imagen cuyo nombre es coincidente con el de la textura indicada, se cargará automáticamente como imagen de retrato..
        /// </summary>
        internal static string AutoAssignPortrait {
            get {
                return ResourceManager.GetString("AutoAssignPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la imagen no es válido. Debe ser de 128x160 píxeles..
        /// </summary>
        internal static string BitmapSizeNotValid {
            get {
                return ResourceManager.GetString("BitmapSizeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que los retratos de la pantalla de selección de personaje se exporten es necesario seleccionar una copia válida de common5.pac (common5_en.pac) de Super Smash Bros. Brawl. Por favor, indica la ruta a continuación.
        /// </summary>
        internal static string Common5Required {
            get {
                return ResourceManager.GetString("Common5Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traje {0}.
        /// </summary>
        internal static string DefaultOutfitName {
            get {
                return ResourceManager.GetString("DefaultOutfitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Detectado).
        /// </summary>
        internal static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar la textura: {0}.
        /// </summary>
        internal static string ErrorAsigningTexture {
            get {
                return ResourceManager.GetString("ErrorAsigningTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al exportar la estructura de directorios.
        /// </summary>
        internal static string ErrorExporting {
            get {
                return ResourceManager.GetString("ErrorExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATENCIÓN: {0} necesita que sus texturas PCS vengan acompañadas de su correspondiente archivo .PAC, pero éste no ha sido encontrado y ha ocurrido un error al intentar generarlo automáticamente.
        ///
        ///Asegúrate de que existe un archivo llamado {1} en la misma carpeta donde se encuentra {2}. De otro modo, es muy probable que el juego se congele durante la partida. No obstante, la información PCS se ha añadido correctamente..
        /// </summary>
        internal static string ErrorGeneratingPacData {
            get {
                return ResourceManager.GetString("ErrorGeneratingPacData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al importar la estructura de directorios. Por favor, verifica que la estructura que estás importando es válida..
        /// </summary>
        internal static string ErrorImporting {
            get {
                return ResourceManager.GetString("ErrorImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar el archivo. Comprueba que el formato sea válido (SSBBT binario).
        /// </summary>
        internal static string ErrorLoadingSssbtFile {
            get {
                return ResourceManager.GetString("ErrorLoadingSssbtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar el archivo. No se trata de un archivo SSBBT..
        /// </summary>
        internal static string ErrorNotValidSsbbtFile {
            get {
                return ResourceManager.GetString("ErrorNotValidSsbbtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al abrir el archivo de texturas.
        /// </summary>
        internal static string ErrorOpening {
            get {
                return ResourceManager.GetString("ErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar el archivo de texturas.
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden escribir los datos de la textura para {0}.
        ///
        ///Por favor, verifica que tienes permisos suficientes para escribir en la carpeta de exportación y que los archivos no estén en uso.
        ///
        ///¿Reintentar escribir los datos de esta textura?.
        /// </summary>
        internal static string ErrorWritingTextureData {
            get {
                return ResourceManager.GetString("ErrorWritingTextureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al escribir datos de textura.
        /// </summary>
        internal static string ErrorWritingTextureDataTitle {
            get {
                return ResourceManager.GetString("ErrorWritingTextureDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la excepción.
        /// </summary>
        internal static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecciona la carpeta &quot;pf&quot; de tu tarjeta SD.
        /// </summary>
        internal static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación realizada con éxito a la carpeta {0}.
        /// </summary>
        internal static string ExportedSuccessfully {
            get {
                return ResourceManager.GetString("ExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo de texturas cargado correctamente.
        /// </summary>
        internal static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo de texturas guardado correctamente.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando datos PAC. Por favor, espera....
        /// </summary>
        internal static string GeneratingPacData {
            get {
                return ResourceManager.GetString("GeneratingPacData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecciona la carpeta &quot;pf&quot; de tu tarjeta SD.
        /// </summary>
        internal static string ImportDescription {
            get {
                return ResourceManager.GetString("ImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un {0:P0} de los personajes que se han importado ha tenido que ser recreados desde cero. Esto normalmente indica que estás tratando de importar una estructura de directorios sin metadatos asociados.
        ///
        ///¿Deseas tratar de cargar información adicional desde la estructura de directorios?
        ///
        ///* Si estás empezando de cero, tal vez te interesa tratar de cargar la información adicional usando como fuente la estructura de carpetas que has indicado. Para ello, pulsa &quot;Sí&quot;.
        ///
        ///* Si por el contrario, estás importando dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportFromScratchWarning {
            get {
                return ResourceManager.GetString("ImportFromScratchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importando.
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta del archivo PCS no existe. Por favor, selecciona un archivo PCS existente..
        /// </summary>
        internal static string InvalidPcsPath {
            get {
                return ResourceManager.GetString("InvalidPcsPath", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NotAvailable {
            get {
                object obj = ResourceManager.GetObject("NotAvailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abriendo.
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Outfit {
            get {
                object obj = ResourceManager.GetObject("Outfit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos .PAC.
        /// </summary>
        internal static string PacFiles {
            get {
                return ResourceManager.GetString("PacFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PanelJMNAzul {
            get {
                object obj = ResourceManager.GetObject("PanelJMNAzul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texturas (*.pcs).
        /// </summary>
        internal static string PcsFiles {
            get {
                return ResourceManager.GetString("PcsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, espera....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación de retratos finalizada con éxito.
        /// </summary>
        internal static string PortraitsExportFinished {
            get {
                return ResourceManager.GetString("PortraitsExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los retratos de los personajes no serán exportados.
        /// </summary>
        internal static string PortraitsWontBeExported {
            get {
                return ResourceManager.GetString("PortraitsWontBeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leyendo archivo .PAC.
        /// </summary>
        internal static string ReadingPacFile {
            get {
                return ResourceManager.GetString("ReadingPacFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la carpeta &quot;pf&quot;.
        /// </summary>
        internal static string SelectExportFolder {
            get {
                return ResourceManager.GetString("SelectExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona la carpeta &quot;pf&quot;.
        /// </summary>
        internal static string SelectImportFolder {
            get {
                return ResourceManager.GetString("SelectImportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de Texturizer (*.ssbbt).
        /// </summary>
        internal static string SsbbtFiles {
            get {
                return ResourceManager.GetString("SsbbtFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esctructura de directorios cargada con éxito.
        /// </summary>
        internal static string StructureLoadedSuccessfully {
            get {
                return ResourceManager.GetString("StructureLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las imágenes soportadas.
        /// </summary>
        internal static string SupportedImages {
            get {
                return ResourceManager.GetString("SupportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
