//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texturizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutfitImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutfitImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Texturizer.OutfitImages", typeof(OutfitImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Captain0 {
            get {
                object obj = ResourceManager.GetObject("Captain0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captain1 {
            get {
                object obj = ResourceManager.GetObject("Captain1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captain2 {
            get {
                object obj = ResourceManager.GetObject("Captain2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captain3 {
            get {
                object obj = ResourceManager.GetObject("Captain3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captain4 {
            get {
                object obj = ResourceManager.GetObject("Captain4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Captain5 {
            get {
                object obj = ResourceManager.GetObject("Captain5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede0 {
            get {
                object obj = ResourceManager.GetObject("Dedede0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede1 {
            get {
                object obj = ResourceManager.GetObject("Dedede1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede2 {
            get {
                object obj = ResourceManager.GetObject("Dedede2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede3 {
            get {
                object obj = ResourceManager.GetObject("Dedede3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede4 {
            get {
                object obj = ResourceManager.GetObject("Dedede4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dedede5 {
            get {
                object obj = ResourceManager.GetObject("Dedede5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy0 {
            get {
                object obj = ResourceManager.GetObject("Diddy0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy1 {
            get {
                object obj = ResourceManager.GetObject("Diddy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy2 {
            get {
                object obj = ResourceManager.GetObject("Diddy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy3 {
            get {
                object obj = ResourceManager.GetObject("Diddy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy4 {
            get {
                object obj = ResourceManager.GetObject("Diddy4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diddy5 {
            get {
                object obj = ResourceManager.GetObject("Diddy5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey0 {
            get {
                object obj = ResourceManager.GetObject("Donkey0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey1 {
            get {
                object obj = ResourceManager.GetObject("Donkey1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey2 {
            get {
                object obj = ResourceManager.GetObject("Donkey2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey3 {
            get {
                object obj = ResourceManager.GetObject("Donkey3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey4 {
            get {
                object obj = ResourceManager.GetObject("Donkey4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Donkey5 {
            get {
                object obj = ResourceManager.GetObject("Donkey5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco0 {
            get {
                object obj = ResourceManager.GetObject("Falco0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco1 {
            get {
                object obj = ResourceManager.GetObject("Falco1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco2 {
            get {
                object obj = ResourceManager.GetObject("Falco2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco3 {
            get {
                object obj = ResourceManager.GetObject("Falco3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco4 {
            get {
                object obj = ResourceManager.GetObject("Falco4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Falco5 {
            get {
                object obj = ResourceManager.GetObject("Falco5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox0 {
            get {
                object obj = ResourceManager.GetObject("Fox0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox1 {
            get {
                object obj = ResourceManager.GetObject("Fox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox2 {
            get {
                object obj = ResourceManager.GetObject("Fox2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox3 {
            get {
                object obj = ResourceManager.GetObject("Fox3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox4 {
            get {
                object obj = ResourceManager.GetObject("Fox4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fox5 {
            get {
                object obj = ResourceManager.GetObject("Fox5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch0 {
            get {
                object obj = ResourceManager.GetObject("GameWatch0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch1 {
            get {
                object obj = ResourceManager.GetObject("GameWatch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch2 {
            get {
                object obj = ResourceManager.GetObject("GameWatch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch3 {
            get {
                object obj = ResourceManager.GetObject("GameWatch3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch4 {
            get {
                object obj = ResourceManager.GetObject("GameWatch4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GameWatch5 {
            get {
                object obj = ResourceManager.GetObject("GameWatch5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon0 {
            get {
                object obj = ResourceManager.GetObject("Ganon0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon1 {
            get {
                object obj = ResourceManager.GetObject("Ganon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon2 {
            get {
                object obj = ResourceManager.GetObject("Ganon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon3 {
            get {
                object obj = ResourceManager.GetObject("Ganon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon4 {
            get {
                object obj = ResourceManager.GetObject("Ganon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ganon5 {
            get {
                object obj = ResourceManager.GetObject("Ganon5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike0 {
            get {
                object obj = ResourceManager.GetObject("Ike0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike1 {
            get {
                object obj = ResourceManager.GetObject("Ike1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike2 {
            get {
                object obj = ResourceManager.GetObject("Ike2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike3 {
            get {
                object obj = ResourceManager.GetObject("Ike3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike4 {
            get {
                object obj = ResourceManager.GetObject("Ike4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ike5 {
            get {
                object obj = ResourceManager.GetObject("Ike5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby0 {
            get {
                object obj = ResourceManager.GetObject("Kirby0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby1 {
            get {
                object obj = ResourceManager.GetObject("Kirby1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby2 {
            get {
                object obj = ResourceManager.GetObject("Kirby2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby3 {
            get {
                object obj = ResourceManager.GetObject("Kirby3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby4 {
            get {
                object obj = ResourceManager.GetObject("Kirby4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kirby5 {
            get {
                object obj = ResourceManager.GetObject("Kirby5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa0 {
            get {
                object obj = ResourceManager.GetObject("Koopa0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa1 {
            get {
                object obj = ResourceManager.GetObject("Koopa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa2 {
            get {
                object obj = ResourceManager.GetObject("Koopa2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa3 {
            get {
                object obj = ResourceManager.GetObject("Koopa3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa4 {
            get {
                object obj = ResourceManager.GetObject("Koopa4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Koopa5 {
            get {
                object obj = ResourceManager.GetObject("Koopa5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link0 {
            get {
                object obj = ResourceManager.GetObject("Link0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link1 {
            get {
                object obj = ResourceManager.GetObject("Link1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link2 {
            get {
                object obj = ResourceManager.GetObject("Link2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link3 {
            get {
                object obj = ResourceManager.GetObject("Link3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link4 {
            get {
                object obj = ResourceManager.GetObject("Link4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link5 {
            get {
                object obj = ResourceManager.GetObject("Link5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucario0 {
            get {
                object obj = ResourceManager.GetObject("Lucario0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucario1 {
            get {
                object obj = ResourceManager.GetObject("Lucario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucario2 {
            get {
                object obj = ResourceManager.GetObject("Lucario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucario3 {
            get {
                object obj = ResourceManager.GetObject("Lucario3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucario4 {
            get {
                object obj = ResourceManager.GetObject("Lucario4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas0 {
            get {
                object obj = ResourceManager.GetObject("Lucas0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas1 {
            get {
                object obj = ResourceManager.GetObject("Lucas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas2 {
            get {
                object obj = ResourceManager.GetObject("Lucas2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas3 {
            get {
                object obj = ResourceManager.GetObject("Lucas3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas4 {
            get {
                object obj = ResourceManager.GetObject("Lucas4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lucas5 {
            get {
                object obj = ResourceManager.GetObject("Lucas5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi0 {
            get {
                object obj = ResourceManager.GetObject("Luigi0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi1 {
            get {
                object obj = ResourceManager.GetObject("Luigi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi2 {
            get {
                object obj = ResourceManager.GetObject("Luigi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi3 {
            get {
                object obj = ResourceManager.GetObject("Luigi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi4 {
            get {
                object obj = ResourceManager.GetObject("Luigi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Luigi5 {
            get {
                object obj = ResourceManager.GetObject("Luigi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario0 {
            get {
                object obj = ResourceManager.GetObject("Mario0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario1 {
            get {
                object obj = ResourceManager.GetObject("Mario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario2 {
            get {
                object obj = ResourceManager.GetObject("Mario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario3 {
            get {
                object obj = ResourceManager.GetObject("Mario3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario4 {
            get {
                object obj = ResourceManager.GetObject("Mario4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mario5 {
            get {
                object obj = ResourceManager.GetObject("Mario5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth0 {
            get {
                object obj = ResourceManager.GetObject("Marth0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth1 {
            get {
                object obj = ResourceManager.GetObject("Marth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth2 {
            get {
                object obj = ResourceManager.GetObject("Marth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth3 {
            get {
                object obj = ResourceManager.GetObject("Marth3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth4 {
            get {
                object obj = ResourceManager.GetObject("Marth4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Marth5 {
            get {
                object obj = ResourceManager.GetObject("Marth5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight0 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight1 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight2 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight3 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight4 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaKnight5 {
            get {
                object obj = ResourceManager.GetObject("MetaKnight5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness0 {
            get {
                object obj = ResourceManager.GetObject("Ness0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness1 {
            get {
                object obj = ResourceManager.GetObject("Ness1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness2 {
            get {
                object obj = ResourceManager.GetObject("Ness2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness3 {
            get {
                object obj = ResourceManager.GetObject("Ness3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness4 {
            get {
                object obj = ResourceManager.GetObject("Ness4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ness5 {
            get {
                object obj = ResourceManager.GetObject("Ness5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach0 {
            get {
                object obj = ResourceManager.GetObject("Peach0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach1 {
            get {
                object obj = ResourceManager.GetObject("Peach1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach2 {
            get {
                object obj = ResourceManager.GetObject("Peach2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach3 {
            get {
                object obj = ResourceManager.GetObject("Peach3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach4 {
            get {
                object obj = ResourceManager.GetObject("Peach4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peach5 {
            get {
                object obj = ResourceManager.GetObject("Peach5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikachu0 {
            get {
                object obj = ResourceManager.GetObject("Pikachu0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikachu1 {
            get {
                object obj = ResourceManager.GetObject("Pikachu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikachu2 {
            get {
                object obj = ResourceManager.GetObject("Pikachu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikachu3 {
            get {
                object obj = ResourceManager.GetObject("Pikachu3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin0 {
            get {
                object obj = ResourceManager.GetObject("Pikmin0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin1 {
            get {
                object obj = ResourceManager.GetObject("Pikmin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin2 {
            get {
                object obj = ResourceManager.GetObject("Pikmin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin3 {
            get {
                object obj = ResourceManager.GetObject("Pikmin3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin4 {
            get {
                object obj = ResourceManager.GetObject("Pikmin4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pikmin5 {
            get {
                object obj = ResourceManager.GetObject("Pikmin5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit0 {
            get {
                object obj = ResourceManager.GetObject("Pit0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit1 {
            get {
                object obj = ResourceManager.GetObject("Pit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit2 {
            get {
                object obj = ResourceManager.GetObject("Pit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit3 {
            get {
                object obj = ResourceManager.GetObject("Pit3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit4 {
            get {
                object obj = ResourceManager.GetObject("Pit4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pit5 {
            get {
                object obj = ResourceManager.GetObject("Pit5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeFushigisou0 {
            get {
                object obj = ResourceManager.GetObject("PokeFushigisou0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeFushigisou1 {
            get {
                object obj = ResourceManager.GetObject("PokeFushigisou1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeFushigisou2 {
            get {
                object obj = ResourceManager.GetObject("PokeFushigisou2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeFushigisou3 {
            get {
                object obj = ResourceManager.GetObject("PokeFushigisou3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeFushigisou4 {
            get {
                object obj = ResourceManager.GetObject("PokeFushigisou4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeLizardon0 {
            get {
                object obj = ResourceManager.GetObject("PokeLizardon0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeLizardon1 {
            get {
                object obj = ResourceManager.GetObject("PokeLizardon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeLizardon2 {
            get {
                object obj = ResourceManager.GetObject("PokeLizardon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeLizardon3 {
            get {
                object obj = ResourceManager.GetObject("PokeLizardon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeLizardon4 {
            get {
                object obj = ResourceManager.GetObject("PokeLizardon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeTrainer0 {
            get {
                object obj = ResourceManager.GetObject("PokeTrainer0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeTrainer1 {
            get {
                object obj = ResourceManager.GetObject("PokeTrainer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeTrainer2 {
            get {
                object obj = ResourceManager.GetObject("PokeTrainer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeTrainer3 {
            get {
                object obj = ResourceManager.GetObject("PokeTrainer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeTrainer4 {
            get {
                object obj = ResourceManager.GetObject("PokeTrainer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeZenigame0 {
            get {
                object obj = ResourceManager.GetObject("PokeZenigame0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeZenigame1 {
            get {
                object obj = ResourceManager.GetObject("PokeZenigame1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeZenigame2 {
            get {
                object obj = ResourceManager.GetObject("PokeZenigame2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeZenigame3 {
            get {
                object obj = ResourceManager.GetObject("PokeZenigame3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PokeZenigame4 {
            get {
                object obj = ResourceManager.GetObject("PokeZenigame4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo0 {
            get {
                object obj = ResourceManager.GetObject("Popo0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo1 {
            get {
                object obj = ResourceManager.GetObject("Popo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo2 {
            get {
                object obj = ResourceManager.GetObject("Popo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo3 {
            get {
                object obj = ResourceManager.GetObject("Popo3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo4 {
            get {
                object obj = ResourceManager.GetObject("Popo4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Popo5 {
            get {
                object obj = ResourceManager.GetObject("Popo5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purin0 {
            get {
                object obj = ResourceManager.GetObject("Purin0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purin1 {
            get {
                object obj = ResourceManager.GetObject("Purin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purin2 {
            get {
                object obj = ResourceManager.GetObject("Purin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purin3 {
            get {
                object obj = ResourceManager.GetObject("Purin3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purin4 {
            get {
                object obj = ResourceManager.GetObject("Purin4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot0 {
            get {
                object obj = ResourceManager.GetObject("Robot0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot1 {
            get {
                object obj = ResourceManager.GetObject("Robot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot2 {
            get {
                object obj = ResourceManager.GetObject("Robot2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot3 {
            get {
                object obj = ResourceManager.GetObject("Robot3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot4 {
            get {
                object obj = ResourceManager.GetObject("Robot4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Robot5 {
            get {
                object obj = ResourceManager.GetObject("Robot5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus0 {
            get {
                object obj = ResourceManager.GetObject("Samus0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus1 {
            get {
                object obj = ResourceManager.GetObject("Samus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus2 {
            get {
                object obj = ResourceManager.GetObject("Samus2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus3 {
            get {
                object obj = ResourceManager.GetObject("Samus3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus4 {
            get {
                object obj = ResourceManager.GetObject("Samus4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Samus5 {
            get {
                object obj = ResourceManager.GetObject("Samus5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik0 {
            get {
                object obj = ResourceManager.GetObject("Sheik0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik1 {
            get {
                object obj = ResourceManager.GetObject("Sheik1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik2 {
            get {
                object obj = ResourceManager.GetObject("Sheik2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik3 {
            get {
                object obj = ResourceManager.GetObject("Sheik3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik4 {
            get {
                object obj = ResourceManager.GetObject("Sheik4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sheik5 {
            get {
                object obj = ResourceManager.GetObject("Sheik5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake0 {
            get {
                object obj = ResourceManager.GetObject("Snake0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake1 {
            get {
                object obj = ResourceManager.GetObject("Snake1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake2 {
            get {
                object obj = ResourceManager.GetObject("Snake2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake3 {
            get {
                object obj = ResourceManager.GetObject("Snake3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake4 {
            get {
                object obj = ResourceManager.GetObject("Snake4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snake5 {
            get {
                object obj = ResourceManager.GetObject("Snake5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic0 {
            get {
                object obj = ResourceManager.GetObject("Sonic0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic1 {
            get {
                object obj = ResourceManager.GetObject("Sonic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic2 {
            get {
                object obj = ResourceManager.GetObject("Sonic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic3 {
            get {
                object obj = ResourceManager.GetObject("Sonic3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sonic4 {
            get {
                object obj = ResourceManager.GetObject("Sonic4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit0 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit1 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit2 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit3 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit4 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SZeroSuit5 {
            get {
                object obj = ResourceManager.GetObject("SZeroSuit5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink0 {
            get {
                object obj = ResourceManager.GetObject("ToonLink0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink1 {
            get {
                object obj = ResourceManager.GetObject("ToonLink1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink2 {
            get {
                object obj = ResourceManager.GetObject("ToonLink2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink3 {
            get {
                object obj = ResourceManager.GetObject("ToonLink3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink4 {
            get {
                object obj = ResourceManager.GetObject("ToonLink4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToonLink5 {
            get {
                object obj = ResourceManager.GetObject("ToonLink5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario0 {
            get {
                object obj = ResourceManager.GetObject("Wario0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario1 {
            get {
                object obj = ResourceManager.GetObject("Wario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario10 {
            get {
                object obj = ResourceManager.GetObject("Wario10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario11 {
            get {
                object obj = ResourceManager.GetObject("Wario11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario2 {
            get {
                object obj = ResourceManager.GetObject("Wario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario3 {
            get {
                object obj = ResourceManager.GetObject("Wario3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario4 {
            get {
                object obj = ResourceManager.GetObject("Wario4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario5 {
            get {
                object obj = ResourceManager.GetObject("Wario5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario6 {
            get {
                object obj = ResourceManager.GetObject("Wario6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario7 {
            get {
                object obj = ResourceManager.GetObject("Wario7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario8 {
            get {
                object obj = ResourceManager.GetObject("Wario8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wario9 {
            get {
                object obj = ResourceManager.GetObject("Wario9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf0 {
            get {
                object obj = ResourceManager.GetObject("Wolf0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf1 {
            get {
                object obj = ResourceManager.GetObject("Wolf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf2 {
            get {
                object obj = ResourceManager.GetObject("Wolf2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf3 {
            get {
                object obj = ResourceManager.GetObject("Wolf3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf4 {
            get {
                object obj = ResourceManager.GetObject("Wolf4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wolf5 {
            get {
                object obj = ResourceManager.GetObject("Wolf5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi0 {
            get {
                object obj = ResourceManager.GetObject("Yoshi0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi1 {
            get {
                object obj = ResourceManager.GetObject("Yoshi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi2 {
            get {
                object obj = ResourceManager.GetObject("Yoshi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi3 {
            get {
                object obj = ResourceManager.GetObject("Yoshi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi4 {
            get {
                object obj = ResourceManager.GetObject("Yoshi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yoshi5 {
            get {
                object obj = ResourceManager.GetObject("Yoshi5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda0 {
            get {
                object obj = ResourceManager.GetObject("Zelda0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda1 {
            get {
                object obj = ResourceManager.GetObject("Zelda1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda2 {
            get {
                object obj = ResourceManager.GetObject("Zelda2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda3 {
            get {
                object obj = ResourceManager.GetObject("Zelda3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda4 {
            get {
                object obj = ResourceManager.GetObject("Zelda4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zelda5 {
            get {
                object obj = ResourceManager.GetObject("Zelda5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
